### PR TITLE
Redirect page change

### PR DESCRIPTION
**Pull request by deneha**
Please do not accept this pull request until @tysonn directs to do so.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@deneha__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
Can we avoid the "best-practices" in the url? I would rather see "guidance".

**Comment by bennage** [comment]
I would like to avoid it in all of the urls.

**Comment by deneha** [comment]
@bennage These were the instructions from @tysonn for this work.  Maybe circle back with him?

**Pull request closed without merging**
