### PR TITLE
Elasticsearch resilience tests

### PR DESCRIPTION
**Pull request by JohnPWSharp**
First draft: Docs and Scripts

### CODE REVIEW

**Comment by bennage** [comment]
I'm still seeing the CLA required label...

**Comment by bennage** [comment]
@dragon119 Can we do this work against the azure-content? 
I think it will be significantly less churn.

**Comment by dragon119** [comment]
@bennage This is the one we didn't publish yet.

**Comment by bennage** [comment]
All 8 of the docs are in the content repo in one form or another. We've also done some of the painful work of prepping them for acom. I don't want ot repeat that work.

**Pull request closed without merging**
