### PR TITLE
Update API-security.md

### PR DESCRIPTION
**Pull request by chriskburns**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chriskburns__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by mekoda** [comment]
Hi @chriskburns, sorry for the late reply and thanks for the contribution.

The main goal of adding the links to the documentation is accomplished. However, would you do this using Git Markdown to match how other documents are authored? [E.g](https://github.com/mspnp/performance-optimization/blob/master/ChattyIO/docs/ChattyIO.md#load-testing-the-application) (reference to "Consequences of this solution").

**Comment by mj1856** [comment]
Yes, please update this to simplify.

Anchors should just be established as:

```html
<a name="anchor"></a>
```

And links to anchors should be in markdown as:

```markdown
[#anchor]
```

**Comment by bennage** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
