### PR TITLE
Amended code examples to use IHttpActionResult. Updated material covering Persistent connections. Updated section covering Expect headers and Continue messages

### PR DESCRIPTION
**Pull request by JohnPWSharp**
These updates relate to Issue #3

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JohnPWSharp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by JohnPWSharp** [comment]
The changes for persistent connections relate to issue #12

**Comment by JohnPWSharp** [comment]
The changes for Expect headers and Continue messages relate to issue #11

**Comment by bennage** [comment]
This is on our backlog to review.

**Comment by JohnPWSharp** [comment]
The change to the return type of DeleteCustomer follows Andrew's review

**Comment by bennage** [comment]
This addresses the feedback in #11 and #12.

**Comment by darrelmiller** [comment]
@bennage Changes look good.  I added a few comments to the commits.

**Comment by JohnPWSharp** [comment]
I have addressed the comments from Darrel in the latest PR.

**Comment by JohnPWSharp** [comment]
@bennage @dragon119 Back to you guys for review

**Comment by mj1856** [comment]
Is there a reason we are using italics for inline code instead of markdown's inline code formatting?

Ex: We use _IHttpActionResult_ instead of the usual convention of `IHttpActionResult`

**Comment by bennage** [comment]
:thumbsup:

**Pull request merged**
