### PR TITLE
removing content that we migrated to azure/azure-content

### PR DESCRIPTION
**Pull request by bennage**

### CODE REVIEW

**Comment by bennage** [comment]
@dragon119 please review

**Comment by enghch** [comment]
Is there a link somewhere so we can get this content in its new location on Azure?

**Comment by bennage** [comment]
@enghch The readme file in this PR points to the new locations.

**Comment by bennage** [comment]
Here's the readme: https://github.com/mspnp/azure-guidance/blob/bennage/migration-to-acom/README.md

**Comment by enghch** [comment]
OK, cool. I see them. Thanks!

**Pull request merged**
